# Multi-Account Trading Bot Configuration
# Each account = one user/client with full isolation

# Multi-account support: add as many accounts as needed
# Each account has own API keys, environment, risk limits, and strategies
accounts:
  # Account 1 (ID: 1)
  - id: 1
    name: "Iurii Demo"
    api_key_env: "1_BYBIT_API_KEY"       # Env var: 1_BYBIT_API_KEY
    api_secret_env: "1_BYBIT_API_SECRET"
    demo_trading: true                   # Demo environment (virtual money)
    dry_run: false                       # Real API calls (to demo server)

    # Per-account risk management
    risk_management:
      mm_rate_threshold: 90.0            # Emergency close when Account MM Rate >= this % (default: 90)

    # Strategies for this account
    strategies:
      - symbol: "DOGEUSDT"
        category: "linear"
        leverage: 75
        initial_position_size_usd: 1.0   # MARGIN in USD (leverage applied automatically!)
        grid_step_percent: 1.0           # Grid step %
        averaging_multiplier: 2.0        # Position multiplier
        take_profit_percent: 1.0         # Take profit %
        max_grid_levels_per_side: 10

      # - symbol: "TONUSDT"
      #   category: "linear"
      #   leverage: 50
      #   initial_position_size_usd: 1.0
      #   grid_step_percent: 1.0
      #   averaging_multiplier: 2.0
      #   take_profit_percent: 1.0
      #   max_grid_levels_per_side: 10

  # Account 2 (ID: 2) - Example for second user
  # Uncomment to add second account:
  # - id: 2
  #   name: "Demo Account 2"
  #   api_key_env: "2_BYBIT_API_KEY"
  #   api_secret_env: "2_BYBIT_API_SECRET"
  #   demo_trading: true
  #   dry_run: false
  #
  #   strategies:
  #     - symbol: "SOLUSDT"
  #       category: "linear"
  #       leverage: 100
  #       initial_position_size_usd: 1.0
  #       grid_step_percent: 1.0
  #       averaging_multiplier: 2.0
  #       take_profit_percent: 1.0
  #       max_grid_levels_per_side: 8

# Global bot settings
bot:
  log_level: "INFO"              # DEBUG | INFO | WARNING | ERROR

# DEPRECATED SETTINGS (no longer used):
# - exchange.demo_trading -> moved to per-account
# - risk_management.max_total_exposure -> uses totalAvailableBalance from exchange
# - risk_management.liquidation_buffer -> uses Account MM Rate (>= 90%)
