# Multi-Account Trading Bot Configuration
# Each account = one user/client with full isolation

# Multi-account support: add as many accounts as needed
# Each account has own API keys, environment, risk limits, and strategies

############################################################################################
#
# Оптимальный набор (низкая корреляция):
#   1. SOLUSDT      # Layer-1, DeFi/NFT (корр. 0.3-0.5 с BTC)
#   2. DOGEUSDT     # Мем-коин, соцсети (корр. 0.2-0.4 с BTC)
#   3. LINKUSDT     # Оракулы, инфра (корр. 0.4-0.6 с BTC)
#   4. AVAXUSDT     # Layer-1 конкурент (корр. 0.5-0.7 с BTC)
#
# Корреляционная матрица (примерно):
#              SOL   DOGE  LINK  AVAX
#   SOL        1.0   0.3   0.4   0.6
#   DOGE       0.3   1.0   0.2   0.4
#   LINK       0.4   0.2   1.0   0.5
#   AVAX       0.6   0.4   0.5   1.0
#
# Почему это хорошо:
#   - DOGE + LINK: корреляция 0.2 (отлично!)
#   - SOL + DOGE: корреляция 0.3 (отлично!)
#   - Все 4 из разных секторов
#   - При тренде BTC движутся по-разном
#
# Для теста (ШИТКОИНЫ):
#   1. 1000PEPEUSDT   # Экстремальная волатильность, тест Panic Mode
#   2. GALAUSDT       # Низкая ликвидность, slippage тест
#   2. 1000FLOKIUSDT  # Альтернатива PEPE с меньшей ликвидностью
#
############################################################################################

accounts:
  # Account 1 (ID: 1)
  - id: 1
    name: "Iurii Demo"
    api_key_env: "1_BYBIT_API_KEY"       # Env var: 1_BYBIT_API_KEY
    api_secret_env: "1_BYBIT_API_SECRET"
    demo_trading: true                   # Demo environment (virtual money)
    dry_run: false                       # Real API calls (to demo server)

    # Per-account risk management
    risk_management:
      mm_rate_threshold: 90.0            # Emergency close when Account MM Rate >= this % (default: 90)
      balance_buffer_percent: 15.0       # Safety buffer for reserve checks - % (default: 15)

    # Strategies for this account
    strategies:
      - symbol: "DOGEUSDT"
        category: "linear"
        leverage: 75
        initial_position_size_usd: 1.0   # MARGIN in USD (leverage applied automatically!)
        grid_step_percent: 1.0           # Grid step %
        averaging_multiplier: 2.0        # Position multiplier
        take_profit_percent: 1.0         # Take profit %
        max_grid_levels_per_side: 10

      # - symbol: "TONUSDT"
      #   category: "linear"
      #   leverage: 50
      #   initial_position_size_usd: 1.0
      #   grid_step_percent: 1.0
      #   averaging_multiplier: 2.0
      #   take_profit_percent: 1.0
      #   max_grid_levels_per_side: 10

  # Account 2 (ID: 2)
  - id: 2
    name: "Andrii Demo"
    api_key_env: "2_BYBIT_API_KEY"
    api_secret_env: "2_BYBIT_API_SECRET"
    demo_trading: true
    dry_run: false

    # Per-account risk management
    risk_management:
      mm_rate_threshold: 90.0            # Emergency close when Account MM Rate >= this % (default: 90)
      balance_buffer_percent: 15.0       # Safety buffer for reserve checks - % (default: 15)

    strategies:
      - symbol: "ETHUSDT"
        category: "linear"
        leverage: 100
        initial_position_size_usd: 1.0
        grid_step_percent: 1.0
        averaging_multiplier: 2.0
        take_profit_percent: 1.0
        max_grid_levels_per_side: 10

  # Account 2 (ID: 2)
  - id: 3
    name: "FLOKI Demo"
    api_key_env: "3_BYBIT_API_KEY"
    api_secret_env: "3_BYBIT_API_SECRET"
    demo_trading: true
    dry_run: false

    # Per-account risk management
    risk_management:
      mm_rate_threshold: 90.0            # Emergency close when Account MM Rate >= this % (default: 90)
      balance_buffer_percent: 15.0       # Safety buffer for reserve checks - % (default: 15)

    strategies:
      - symbol: "1000FLOKIUSDT"
        category: "linear"
        leverage: 50
        initial_position_size_usd: 1.0
        grid_step_percent: 1.0
        averaging_multiplier: 2.0
        take_profit_percent: 1.0
        max_grid_levels_per_side: 10

# Global bot settings
bot:
  log_level: "DEBUG"             # DEBUG | INFO | WARNING | ERROR

# DEPRECATED SETTINGS (no longer used):
# - exchange.demo_trading -> moved to per-account
# - risk_management.max_total_exposure -> uses totalAvailableBalance from exchange
# - risk_management.liquidation_buffer -> uses Account MM Rate (>= 90%)
